Repository oceanprotocol/market, pull requests merged in 2022-03, with the labels that each got.

#1047 Restore trade tab
  package-lock.json
  package.json
  src/@context/Pool/_queries.ts
  src/@context/Pool/_types.ts
  src/@context/Pool/index.tsx
  src/@types/node_modules.d.ts
  src/@utils/constants.ts
  src/@utils/nft.ts
  src/components/@shared/FormFields/FilesInput/index.tsx
  src/components/@shared/atoms/Blockies.tsx
  src/components/Asset/AssetActions/Pool/index.tsx
  src/components/Asset/AssetActions/Trade/FormTrade.tsx
  src/components/Asset/AssetActions/Trade/Output.tsx
  src/components/Asset/AssetActions/Trade/Swap.tsx
  src/components/Asset/AssetActions/Trade/TradeInput.module.css
  src/components/Asset/AssetActions/Trade/TradeInput.tsx
  src/components/Asset/AssetActions/Trade/_constants.ts
  src/components/Asset/AssetActions/Trade/_types.ts
  src/components/Asset/AssetActions/Trade/index.tsx
Labels: Priority: High

#1167 Feat: add final did to tokenURI in NFT metadata
  src/@utils/nft.ts
  src/components/Publish/index.tsx
Labels: Type: Enhancement

#1247 Fix: hardcoded SVG width/height in NFT image
  src/@utils/SvgWaves.ts
Labels: Type: Bug
